### ISSUE TITLE
Not working with TypeDoc 0.20

### ISSUE THREAD

**Issue by felipecrs** [jonchardy/typedoc-plugin-no-inherit#20]
This plugin seems to be amazing, but for some reason it doesn't work here.

![us0djoxvCX](https://user-images.githubusercontent.com/29582865/110067458-865d8c00-7d52-11eb-9268-37e18ce37910.gif)

I'm opening this issue so I don't forget, I know I'll probably have to provide more information to you, but by looking to my GIF, do you see anything wrong?

**Comment by jonchardy** [comment]
Are you using Typedoc 0.20.x? It seems something was broken regarding inheritance, as reflections the plugin examines no longer have the inheritedFrom property set. Still seems to work with 0.19.x as a workaround for now.

**Comment by jonchardy** [comment]
I've updated the package to limit the Typedoc peer dependency version and logged https://github.com/TypeStrong/typedoc/issues/1527.

**Comment by felipecrs** [comment]
> Are you using Typedoc 0.20.x?

Yes

> Still seems to work with 0.19.x as a workaround for now.

> I've updated the package to limit the Typedoc peer dependency version and logged TypeStrong/typedoc#1527.

Ok, thank you. :)

**Comment by Gerrit0** [comment]
I suspect this may be fixed now - https://github.com/TypeStrong/typedoc/issues/1527 has been resolved.

**Comment by D4nte** [comment]
> I've updated the package to limit the Typedoc peer dependency version and logged [TypeStrong/typedoc#1527](https://github.com/TypeStrong/typedoc/issues/1527).

Could this change be reverted now that https://github.com/TypeStrong/typedoc/issues/1527 is closed?

**Comment by jonchardy** [comment]
This should be resolved with 1.3. There were some code changes required with the new way Typedoc does things.
