### ISSUE TITLE
Should also take effect on accessors

### ISSUE THREAD

**Issue by kainino0x** [jonchardy/typedoc-plugin-no-inherit#25]
This is a really handy plugin, thanks!

I found that while it behaves as expected for methods and fields, it doesn't work on accessors (getters, e.g. `get device()`, and setters, e.g. `set device()`); they still show up in child classes.

**Comment by jonchardy** [comment]
Seems as though TypeDoc's inheritedFrom property on reflections isn't accurate for accessors, at least at the time the declaration is created. I'll look into it.

**Comment by jonchardy** [comment]
Logged https://github.com/TypeStrong/typedoc/issues/1742. This is a TypeDoc bug.

**Comment by jonchardy** [comment]
This has been resolved by TypeDoc v0.22.7.

**Comment by kainino0x** [comment]
Nice! Thank you for filing it!
