### ISSUE TITLE
Static fields are not ignored

### ISSUE THREAD

**Issue by alcuadrado** [jonchardy/typedoc-plugin-no-inherit#8]
Hi @jonchardy !

Thanks for making this plugin! It's super when you are inheriting from built-in classes, like `Error`.

Unfortunately, it doesn't ignore inherited static fields. When inheriting from `Error`, I get a static field `Error` pointing to https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L984 

This is how it looks:
![image](https://user-images.githubusercontent.com/176499/53673979-a2ad2680-3c69-11e9-807e-79e30e7c83fc.png)

Note that the line number in the link is changed to match the line in my local version.

If you give me some guidance I can try to fix this.

Thanks,
Patricio

**Comment by jonchardy** [comment]
Apologies for the delay on this. I've looked into it, and it seems like something is going on with the way Typedoc identifies inheritance. You'll notice that even if you toggle the Inherited checkbox option, Error will still be displayed.

I'll log a Typedoc issue to see if we can figure out what's going on.

**Comment by jonchardy** [comment]
Closing as this is a problem with Typedoc.
